version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u migue --password=1234567" ]
      interval: 30s
      timeout: 10s
      retries: 5
  spring-img-test:
    container_name: spring-api-container
    image: spring-img-test
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"

volumes:
  mysql-volume:
networks:
  spring-network:



